### ISSUE TITLE
web player?

### ISSUE THREAD

**Issue by severak** [Nintorac/NeuralDX7#1]
hi,
I have one idea how to improve your site - add [javascript version of Dexed](https://www.webaudiomodules.org/wamsynths/dexed) to  the page to be able to test presets right from the browser.

**Comment by Nintorac** [comment]
Hey, 
it is a good idea but a bit out of my area of expertise to implement, I was just barely able to get what is there up!!

Though if you would like to create a website for yourself I would be happy for you to use the generation endpoint [https://generate.thisdx7cartdoesnotexist.com/](https://generate.thisdx7cartdoesnotexist.com/) 

:)

**Comment by atsushieno** [comment]
You can also use my juce_emscripten port https://juce-demos.atsushieno.dev/standalone/dexed/Dexed.html (sources are also available at https://github.com/atsushieno/dexed/tree/emscripten)
