### ISSUE TITLE
Use https://generate.thisdx7cartdoesnotexist.com/ from my Patch editor?

### ISSUE THREAD

**Issue by agawley** [Nintorac/NeuralDX7#3]
Hi. I'm building a patch editor for DX7 / Volca FM in Max for Live. Current version here: https://gumroad.com/l/VolcaFMEditor

In the latest release I'm adding the ability to load and send DX7 Syx Cartridges. I'd love to add the ability to load a unique bank generated by https://generate.thisdx7cartdoesnotexist.com/. Is it okay for me to hit that URL directly from my app? Obvs I will provide a link back and attribution.

**Comment by Nintorac** [comment]
Hey, cool project!

More than happy for you to use the endpoint

**Comment by agawley** [comment]
Done: https://www.mindlesstrx.com/post/volca-fm-editor-huge-update

Thanks!

**Comment by Nintorac** [comment]
Hey,

I was thinking about adding an endpoint that will just generate a single voice. It will also have the option to specify the that latent dimension that generates the voice.

This is essentially 8 numbers between 1 and 0 eg `[0.1, 0.6, 0.2, 0.54, 0.34, 0.12, 0.28, 0.92]` and that will allow a user to tune the voice. 

Would you be interested in implementing something like this into your editor?

Cheers!
